version: '3.3'

services:

  client:
    image: "scaleoutsystems/fedn-dev-client:latest"
    environment:
      - GET_HOSTS_FROM=dns
    working_dir: /app/client
    command: sh -c "python -m venv /venv && /venv/bin/pip install --upgrade pip && /venv/bin/pip install --no-cache-dir -e /app/fedn && /venv/bin/pip install --no-cache-dir tensorflow==2.7.1 && /venv/bin/pip install --no-cache-dir fire==0.3.1 && /venv/bin/pip install --no-cache-dir docker==5.0.2 && mkdir -p /app/client/ && fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ${PWD}/config:/app/client/config
      - ${PWD}/examples/mnist-keras/client:/app/client/client
      - ${HOST_DATA_DIR:-/home/zhulingkai/fedn/examples/mnist-keras/data}:/var/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/fedn:/app/fedn
    deploy:
      replicas: 2

